name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Acessar VM via SSH e deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /caminho/para/repositorio
          git pull origin main
          docker build -t flask-api .
          docker stop flask-api || true
          docker rm flask-api || true
          docker run -d -p 80:80 --name flask-api flask-api
